"""empty message

Revision ID: 1f9efee3467a
Revises: 7d5749d43a74
Create Date: 2023-08-02 14:01:27.989283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f9efee3467a'
down_revision = '7d5749d43a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('column_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('another_column', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('numbers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numbers', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('another_column')
        batch_op.drop_column('column_name')

    op.create_table('test_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('another_column', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
