"""empty message

Revision ID: 3d4489855ba3
Revises: 1f9efee3467a
Create Date: 2023-08-02 14:04:51.505923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d4489855ba3'
down_revision = '1f9efee3467a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('numbers', sa.String(length=100), nullable=False))
        batch_op.drop_column('column_name')
        batch_op.drop_column('another_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_column', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('column_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('numbers')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
