"""empty message

Revision ID: 474d1ecb2356
Revises: fabab8a85aea
Create Date: 2023-07-31 16:59:37.694435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '474d1ecb2356'
down_revision = 'fabab8a85aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('numbers',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predict_result', schema=None) as batch_op:
        batch_op.alter_column('numbers',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
